# 服务端口
server:
  port: 8222
spring:
  application:
    # 服务名
    name: service-gateway
  cloud:
    gateway:
      discovery:
        locator:
          #使用服务发现路由
          enabled: true
      routes:
        - id: service-hosp1
          uri: lb://service-hosp
          predicates:
            - Path=/*/hospital/** # 路径匹配
        - id: service-hosp2
          uri: lb://service-hosp
          predicates:
            - Path=/*/hosp/** # 路径匹配
        - id: service-hosp3
          uri: lb://service-hosp
          predicates:
            - Path=/*/user/** # 路径匹配
        - id: service-cmn
          uri: lb://service-cmn
          predicates:
            - Path=/*/cmn/** # 路径匹配
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/*/userinfo/** # 路径匹配
        - id: service-sms
          uri: lb://service-sms
          predicates:
            - Path=/*/sms/** # 路径匹配
        - id: service-oss
          uri: lb://service-oss
          predicates:
            - Path=/*/oss/** # 路径匹配
        - id: service-order
          uri: lb://service-order
          predicates:
            - Path=/*/order/**
        - id: service-sta
          uri: lb://service-sta
          predicates:
            - Path=/*/statistics/**
        - id: service-hosp4
          uri: lb://service-hosp
          predicates:
            - Path=/admin/** # 路径匹配,兜底的
    nacos:
      discovery:
        # nacos服务地址
        server-addr: localhost:8848
