# 服务端口
server:
  port: 8202
spring:
  # 服务名
  application:
    name: service-cmn
  # nacos
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: lcj6445254
    url: jdbc:mysql://localhost:3307/yygh_cmn?characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
  jackson:
    #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    # 环境设置：dev、test、prod
    active: dev
#  # redis相关设置
  redis:
    host: localhost
    port: 6379
    database:  0
  lettuce:
    pool:
      max-active: 20
      #最大阻塞等待时间(负数表示没限制)
      max-idle: 5
      max-wait: -1
      min-idle: 0