server:
  # 服务端口
  port: 8208

spring:
  application:
    # 服务名
    name: service-task
  profiles:
    # 环境设置：dev、test、prod
    active: dev
  cloud:
    nacos:
      discovery:
        # nacos服务地址
        server-addr: localhost:8848
  #rabbitmq地址
  rabbitmq:
    host: 192.168.6.100
    port: 5672
    username: admin
    password: admin