# 服务端口
server:
  port: 8160

# 服务名
spring:
  application:
    name: service-user
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
      #最大阻塞等待时间(负数表示没限制)
  # 环境设置：dev、test、prod
  profiles:
    active: dev

  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/yygh_user?characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: lcj6445254

  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  #配置mapper xml文件的路径
  mybatis-plus:
    mapper-locations: classpath:com/rain/yygh/user/mapper/xml/*.xml
wx:
  app_id: wxed9954c01bb89b47
  app_secret: a7482517235173ddb4083788de60b90e
  redirect_url: http://localhost:8160/user/userinfo/wx/callback