# 服务端口
server:
  port: 8207

mybatis-plus:
  mapper-locations: classpath:com\rain\yygh\order\mapper\xml\*.xml
# 服务名
spring:
  application:
    name: service-order
  profiles:
    active: dev
  datasource:
    # mysql数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/yygh_order?characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: lcj6445254
  jackson:
    #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    mongodb:
      uri: mongodb://192.168.6.100:27017/test
  cloud:
    nacos:
      # nacos服务地址
      discovery:
        server-addr: localhost:8848

  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1 # 最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0
 # rabbitmq地址
  rabbitmq:
    host: 192.168.6.100
    port: 5672
    username: guest
    password: guest
weixin:
  pay:
    #关联的公众号appid
    appid: wx74862e0dfcf69954
    #商户号
    partner: 1558950191
    #商户key
    partnerkey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb